### ISSUE TITLE
Describe all linters and checkers in README.md

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/cvejob#89]
Describe all linters and checkers we use on CI in README.md file

- docstyle checker
- PEP8 linter
- common errors detection
- dead code detection
- cyclomatix complexity index
- maintenance index

**Comment by tisnik** [comment]
Fixed in https://github.com/fabric8-analytics/cvejob/pull/90

**Comment by msrb** [comment]
@tisnik I've actually moved that section to https://github.com/fabric8-analytics/cvejob/blob/master/docs/development.md#qa-and-coding-standards.
